
[general]
	#Wether ghost blocks are shown when you are holding a framed block
	showGhostBlocks = true
	#Wether certain framed blocks should show fancy hitboxes
	fancyHitboxes = true
	#If false only full block faces of framed blocks will be culled, if true all outer faces of famed blocks can be culled
	detailedCulling = true
	#If true, the UV remapping will use discrete steps to avoid floating point errors
	discreteUVSteps = true
	#Configures how detailed connected textures are supported.
	#Use anything above FULL_FACE at your own risk (performance impact, unexpected behaviour)!
	#If NONE, all connected textures support is disabled
	#If FULL_FACE, connected textures are supported on full faces
	#If FULL_CON_FACE, connected textures are supported as above and on faces whose connecting neighbor covers a full face
	#If DETAILED, connected textures are supported as above and on most faces when interacting with other framed blocks
	#Allowed Values: NONE, FULL_FACE, FULL_CON_FACE, DETAILED
	conTexMode = "FULL_FACE"

