
#Better Fusion Reactor. This config is synced between server and client.
[bfr]
	#Radius of Explosion (default 4 - TNT size)
	reactor_explosion_radius = 4.0

	#Better Fusion Reactor
	[bfr.better_fusion_reactor]
		#How often Reactivity changes and error level change speed. default 10
		#Range: 1 ~ 20
		reaction_difficulty = 10
		#Explosion when reactor reaches 100% error level
		reactor_meltdown = true

